### ISSUE TITLE
Mongoose

### ISSUE THREAD

**Issue by DarrenVictoriano** [DarrenVictoriano/MAD-Protection#4]

**Comment by DarrenVictoriano** [comment]
Create Model for Account:
Collection Name: UserInfo
FirstName
LastName
Email
Password
AccountInfoID: []

Collection: UserInfo
AccountName
UserName
Password
Link
Notes

**Comment by sweetmike** [comment]
userInfoController.js
- findOne (Find a user account) * populate with matching accountInfo
- create (Create a user account)

acctInfoController.js
- create 
- update 
- remove
